### ISSUE TITLE
Tab is not defined in system.xml

### ISSUE THREAD

**Issue by shinesoftware** [WaPoNe/module-cookie-notification#2]
Hello,

add in your system.xml this code:

>     <system>
>         <tab id="wapone" sortOrder="999" translate="label">
>             <label>WaPoNe</label>
>         </tab>
>         .....

regards

**Comment by WaPoNe** [comment]
You're right but in the module README it is written: **If you don't use composer to install the module but you download it directly, you also have to download [https://github.com/WaPoNe/module-wapone-base](https://github.com/WaPoNe/module-wapone-base) module.**
