### ISSUE TITLE
2.3 Compability

### ISSUE THREAD

**Issue by derendo** [WaPoNe/module-cookie-notification#3]
When does your Extension support magento 2.3 ?

**Comment by gaurangpadhiyar007** [comment]
@derendo while you upgrade to Magento 2.3 from 2.2.*, use this command.

composer remove magento/product-community-edition --no-update  wapone/module-cookie-notification
 once upgraded successfully.
Replace composer.json with below code.

> `{
>     "name": "wapone/module-cookie-notification",
>     "description": "Magento 2 extension to inform users about use and management of your website cookies",
>     "type": "magento2-module",
>     "version": "0.0.2",
>     "license": [
>         "OSL-3.0",
>         "AFL-3.0"
>     ],
>     "authors": [{
>         "name": "WaPoNe",
>         "email": "michele@fantetti.net",
>         "homepage": "http://www.fantetti.net",
>         "role": "Developer"
>     }],
>     "autoload": {
>         "files": ["registration.php"],
>         "psr-4": {
>             "WaPoNe\\CookieNotification\\": ""
>         }
>     }
> }
> `



Please let me know if need help on this.

**Comment by WaPoNe** [comment]
@derendo sorry for delay.
The module (version 0.0.3) supports Magento 2.3
